apiVersion: v1
kind: Service
metadata:
  name: {{ include "perforce_discord_bridge.fullname" . }}
  labels:
    {{- include "perforce_discord_bridge.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "perforce_discord_bridge.selectorLabels" . | nindent 4 }}
